# Generated by Django 4.2.6 on 2023-10-19 04:57

import django.db.models.deletion
from django.db import migrations, models

import paper.core.utils.field


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nome do cliente")),
                ("email", models.EmailField(max_length=50, unique=True, verbose_name="E-mail do cliente")),
                ("phone", models.CharField(max_length=20, unique=True, verbose_name="Contato do cliente")),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="CommissionLimit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        unique=True,
                        verbose_name="Dia da Semana",
                    ),
                ),
                (
                    "min_commission_percent",
                    paper.core.utils.field.CommissionPercentField(
                        decimal_places=2,
                        help_text="Deve ser um valor entre 0 e 10",
                        max_digits=4,
                        verbose_name="Porcentagem Mínima",
                    ),
                ),
                (
                    "max_commission_percent",
                    paper.core.utils.field.CommissionPercentField(
                        decimal_places=2,
                        help_text="Deve ser um valor entre 0 e 10",
                        max_digits=4,
                        verbose_name="Porcentagem Máxima",
                    ),
                ),
            ],
            options={
                "verbose_name": "Limite da Comissão",
                "verbose_name_plural": "Limites da Comissão",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20, unique=True, verbose_name="Código")),
                ("description", models.TextField(verbose_name="Descrição")),
                ("price", models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Preço")),
                (
                    "commission_percent",
                    paper.core.utils.field.CommissionPercentField(
                        decimal_places=2, max_digits=4, verbose_name="Porcentagem da comissão"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nfe", models.CharField(max_length=50, unique=True, verbose_name="Código NFE")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora da venda")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="core.client",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=60, verbose_name="Nome do vendedor")),
                ("email", models.EmailField(max_length=50, unique=True, verbose_name="E-mail do vendedor")),
                ("phone", models.CharField(max_length=20, unique=True, verbose_name="Contato do vendedor")),
            ],
            options={
                "verbose_name": "Vendedor",
                "verbose_name_plural": "Vendedores",
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantidade")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Data/hora da venda")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Data/hora da alteração")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="core.product",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.sale",
                        verbose_name="Venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Itens",
            },
        ),
        migrations.AddField(
            model_name="sale",
            name="products",
            field=models.ManyToManyField(
                related_name="sales", through="core.SaleItem", to="core.product", verbose_name="Produtos"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="core.seller",
                verbose_name="Vendedor",
            ),
        ),
    ]
