# Generated by Django 4.2.6 on 2023-10-14 04:31

from django.db import migrations, models

import paper.core.utils.field


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_sale_saleitem_client_and_seller"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionPercentLimit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        unique=True,
                        verbose_name="Dia da semana",
                    ),
                ),
                (
                    "min_commission_percent",
                    paper.core.utils.field.CommissionPercentField(
                        decimal_places=2, max_digits=4, verbose_name="Porcentagem mínima da comissão"
                    ),
                ),
                (
                    "max_commission_percent",
                    paper.core.utils.field.CommissionPercentField(
                        decimal_places=2, max_digits=4, verbose_name="Porcentagem máxima da comissão"
                    ),
                ),
            ],
            options={
                "verbose_name": "Limite Porcentagem da Comissão",
                "verbose_name_plural": "Limites Porcentagem da Comissão",
            },
        ),
        migrations.RemoveField(
            model_name="saleitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="saleitem",
            name="sale",
        ),
        migrations.AlterField(
            model_name="product",
            name="commission_percent",
            field=paper.core.utils.field.CommissionPercentField(
                decimal_places=2, max_digits=4, verbose_name="Porcentagem da comissão"
            ),
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
        migrations.DeleteModel(
            name="SaleItem",
        ),
        migrations.AddField(
            model_name="product",
            name="commission_percent_limits",
            field=models.ManyToManyField(
                to="core.commissionpercentlimit", verbose_name="Limites Porcentagem da Comissão"
            ),
        ),
    ]
